CREATE TABLE IF NOT EXISTS exoplanet.fact_planet_star (
	planet_key INT
	,star_key INT
	,date_key INT
	,planet_mass DOUBLE PRECISION
	,planet_mass_error_min DOUBLE PRECISION
	,planet_mass_error_max DOUBLE PRECISION
	,planet_mass_sini DOUBLE PRECISION
	,planet_mass_sini_error_min DOUBLE PRECISION
	,planet_mass_sini_error_max DOUBLE PRECISION
	,planet_radius DOUBLE PRECISION
	,planet_radius_error_min DOUBLE PRECISION
	,planet_radius_error_max DOUBLE PRECISION
	,planet_orbital_period DOUBLE PRECISION
	,planet_orbital_period_error_min DOUBLE PRECISION
	,planet_orbital_period_error_max DOUBLE PRECISION
	,planet_semi_major_axis DOUBLE PRECISION
	,planet_semi_major_axis_error_min DOUBLE PRECISION
	,planet_semi_major_axis_error_max DOUBLE PRECISION
	,planet_eccentricity DOUBLE PRECISION
	,planet_eccentricity_error_min DOUBLE PRECISION
	,planet_eccentricity_error_max DOUBLE PRECISION
	,planet_inclination DOUBLE PRECISION
	,planet_inclination_error_min DOUBLE PRECISION
	,planet_inclination_error_max DOUBLE PRECISION
	,planet_angular_distance DOUBLE PRECISION
	,planet_omega DOUBLE PRECISION
	,planet_omega_error_min DOUBLE PRECISION
	,planet_omega_error_max DOUBLE PRECISION
	,planet_tperi DOUBLE PRECISION
	,planet_tperi_error_min DOUBLE PRECISION
	,planet_tperi_error_max DOUBLE PRECISION
	,planet_tconj DOUBLE PRECISION
	,planet_tconj_error_min DOUBLE PRECISION
	,planet_tconj_error_max DOUBLE PRECISION
	,planet_tzero_tr DOUBLE PRECISION
	,planet_tzero_tr_error_min DOUBLE PRECISION
	,planet_tzero_tr_error_max DOUBLE PRECISION
	,planet_tzero_tr_sec DOUBLE PRECISION
	,planet_tzero_tr_sec_error_min DOUBLE PRECISION
	,planet_tzero_tr_sec_error_max DOUBLE PRECISION
	,planet_lambda_angle DOUBLE PRECISION
	,planet_lambda_angle_error_min DOUBLE PRECISION
	,planet_lambda_angle_error_max DOUBLE PRECISION
	,planet_impact_parameter DOUBLE PRECISION
	,planet_impact_parameter_error_min DOUBLE PRECISION
	,planet_impact_parameter_error_max DOUBLE PRECISION
	,planet_tzero_vr DOUBLE PRECISION
	,planet_tzero_vr_error_min DOUBLE PRECISION
	,planet_tzero_vr_error_max DOUBLE PRECISION
	,planet_k DOUBLE PRECISION
	,planet_k_error_min DOUBLE PRECISION
	,planet_k_error_max DOUBLE PRECISION
	,planet_temp_calculated DOUBLE PRECISION
	,planet_temp_calculated_error_min DOUBLE PRECISION
	,planet_temp_calculated_error_max DOUBLE PRECISION
	,planet_temp_measured DOUBLE PRECISION
	,planet_hot_point_lon DOUBLE PRECISION
	,planet_geometric_albedo DOUBLE PRECISION
	,planet_geometric_albedo_error_min DOUBLE PRECISION
	,planet_geometric_albedo_error_max DOUBLE PRECISION
	,planet_log_g DOUBLE PRECISION
	,star_ra DOUBLE PRECISION
	,star_dec DOUBLE PRECISION
	,star_mag_v DOUBLE PRECISION
	,star_mag_i DOUBLE PRECISION
	,star_mag_j DOUBLE PRECISION
	,star_mag_h DOUBLE PRECISION
	,star_mag_k DOUBLE PRECISION
	,star_distance DOUBLE PRECISION
	,star_distance_error_min DOUBLE PRECISION
	,star_distance_error_max DOUBLE PRECISION
	,star_metallicity_error_min DOUBLE PRECISION
	,star_metallicity_error_max DOUBLE PRECISION
	,star_mass DOUBLE PRECISION
	,star_mass_error_min DOUBLE PRECISION
	,star_mass_error_max DOUBLE PRECISION
	,star_radius DOUBLE PRECISION
	,star_radius_error_min DOUBLE PRECISION
	,star_radius_error_max DOUBLE PRECISION
	,star_age_error_min DOUBLE PRECISION
	,star_age_error_max DOUBLE PRECISION
	,star_teff_error_min DOUBLE PRECISION
	,star_teff_error_max DOUBLE PRECISION
	,row_entry_date DATE
);